manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: new_zmkfirmware_mouse_support
      url-base: https://github.com/urob/zmk/tree/mouse-3.2
    - name: krikun98
      url-base: https://github.com/krikun98
    - name: ftc
      url-base: https://github.com/ftc
  projects:
    - name: new_zmkfirmware_mouse_support
      remote: urob
      revision: mouse-3.2
      import: app/west.yml
  self:
    path: config
